version: "3.8"
services:
  product:
    build: ./product-service
    ports:
      - "3000:3000"
  customer:
    build: ./customer-service
    ports:
      - "4000:4000"
  inventory:
    build: ./inventory-service
    ports:
      - "5000:5000"